name: "CI"

on:
  push:
    branches: [ "main" ]
    paths-ignore: ["docs/**", "**/README.md", "**/CODE_OF_CONDUCT.md", "**/CONTRIBUTING.md", "**/LICENSE"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**", "**/README.md", "**/CODE_OF_CONDUCT.md", "**/CONTRIBUTING.md", "**/LICENSE"]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  spark_versions_validation:
    strategy:
      matrix:
        spark_version: ['3.2.4', '3.3.2', '3.4.1']
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
        cache: "sbt"
    - env:
        SPARK_VERSION_OVERRIDE: ${{ matrix.spark_version }}
      run: |
        echo "$SPARK_VERSION_OVERRIDE" > project/spark-version.conf
        cat project/spark-version.conf
    - run: sbt compile 
    - run: sbt test 

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: "temurin"
          cache: "sbt"
      - run: sbt compile 
      - run: sbt test 
      - run: sbt package
      - run: tar cf artefacts.tar target/scala-*/*.jar */target/scala-*/*.jar
      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Artefacts
          path: artefacts.tar
