name: "Integration Checks"

on:
  pull_request:
    branches: ["develop"]
    paths-ignore: ["docs/**", "**/README.md", "**/CODE_OF_CONDUCT.md", "**/CONTRIBUTING.md", "**/LICENSE"]
    types:
      - opened
      - reopened
      - synchronize

jobs:
  integration_check_build:
    name: "Integration Check - Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
        cache: "sbt"
    - name: Build
      run: sbt compile 
    - name: Test
      run: sbt test 
