name: "Integration"

on:
  push:
    branches: [ "develop" ]
    paths-ignore: ["docs/**", "**/README.md", "**/CODE_OF_CONDUCT.md", "**/CONTRIBUTING.md", "**/LICENSE"]

jobs:
  integration_build:
    name: "Integration - Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: "temurin"
          cache: "sbt"
      - name: Build
        run: sbt compile 
      - name: Test
        run: sbt test 
      - name: Package
        run: sbt package
      - name: Compress build
        run: tar cf targets.tar target project/target
      - name: Upload build
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: targets.tar

  integration_publish:
    name: "Integration - Publish"
    needs: [integration_build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
        cache: "sbt"
    - name: Download build
      uses: actions/download-artifact@v3
      with:
        name: build
    - name: Unpack build
      run: |
        tar xf targets.tar
        rm targets.tar
    - name: List files in wd
      run: ls -R
    - run: echo "publish release candidate"
